// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASoyRjj7RI_MBdm4XuTzH-KWcyvpo2Zgs',
    appId: '1:862112614226:web:c60d10a969936c5f9e1c8b',
    messagingSenderId: '862112614226',
    projectId: 'carraze-467ef',
    authDomain: 'carraze-467ef.firebaseapp.com',
    storageBucket: 'carraze-467ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRSCfdg0TRQvepGjwQzj8ERSlLREVEy64',
    appId: '1:862112614226:android:c5f324b4a9f058229e1c8b',
    messagingSenderId: '862112614226',
    projectId: 'carraze-467ef',
    storageBucket: 'carraze-467ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASXEK9sJodPA_rUmsbDGZ4KtbiFPK8Bak',
    appId: '1:862112614226:ios:b1b618d64c6f8d2b9e1c8b',
    messagingSenderId: '862112614226',
    projectId: 'carraze-467ef',
    storageBucket: 'carraze-467ef.firebasestorage.app',
    iosBundleId: 'com.example.carraze',
  );
}
